backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "الصفحات"
    files:
      - name: "home"
        label: "الصفحة الرئيسية"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/njk.njk"}
          - {label: "عنوان الموقع", name: "title", widget: "string", required: true}
          - {label: "وصف بسيط أسفل العنوان", name: "subtitle", widget: "string", required: false}
          - {label: "SEO - عنوان الميتا", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO - وصف الميتا", name: "metaDesc", widget: "string", required: false}
          - {label: "صورة التواصل الاجتماعي", name: "socialImage", widget: "image", required: false}
          - label: "الخدمات"
            name: "services"
            widget: "list"
            fields:
              - {label: "اسم الخدمة", name: "name", widget: "string"}
              - {label: "وصف الخدمة", name: "description", widget: "text"}
          - label: "أزرار عائمة"
            name: "floatingButtons"
            widget: "list"
            fields:
              - {label: "نوع الزر (call/whatsapp)", name: "type", widget: "select", options: ["call", "whatsapp"]}
              - {label: "رقم الهاتف أو رابط الواتساب", name: "value", widget: "string"}
              - {label: "نص الزر", name: "label", widget: "string"}
          - {label: "محتوى الصفحة (تفاصيل إضافية)", name: "body", widget: "markdown", required: false}

  - name: "generic_pages"
    label: "صفحات عامة"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "العنوان", name: "title", widget: "string", required: true}
      - {label: "رابط مخصص (اختياري)", name: "permalink", widget: "string", required: false}
      - {label: "SEO - عنوان الميتا", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO - وصف الميتا", name: "metaDesc", widget: "string", required: false}
      - {label: "صورة التواصل الاجتماعي", name: "socialImage", widget: "image", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown"}

  - name: "globals"
    label: "الإعدادات العامة"
    files:
      - label: "بيانات الموقع"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "اسم الموقع", name: "name", widget: "string", required: true}
          - {label: "رابط الموقع", name: "url", widget: "string", required: true}
          - {label: "اسم المؤلف", name: "authorName", widget: "string", required: false}
          - {label: "البريد الإلكتروني للمؤلف", name: "authorEmail", widget: "string", required: false}
          - {label: "وصف قصير للفوتر", name: "shortDesc", widget: "string", required: false}
          - {label: "إظهار حقوق القالب", name: "showThemeCredit", widget: "boolean", default: false}

      - label: "القائمة الرئيسية"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "عناصر القائمة"
            name: "items"
            widget: "list"
            fields:
              - {label: "النص", name: "text", widget: "string", required: true}
              - {label: "الرابط", name: "url", widget: "string", required: true}
              - {label: "هل رابط خارجي؟", name: "external", widget: "boolean", default: false}

      - label: "إعدادات الألوان والخطوط"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        fields:
          - label: "الألوان"
            name: "colors"
            widget: "object"
            fields:
              - {label: "الأزرق الداكن الأساسي", name: "primary", widget: "string", default: "#1A237E"}
              - {label: "تدرج الأزرق الداكن", name: "primaryGradient", widget: "string", default: "linear-gradient(45deg, #283593, #1A237E)"}
              - {label: "النص الأخضر", name: "highlight", widget: "string", default: "#4CAF50"}
              - {label: "لون الخلفية", name: "background", widget: "string", default: "#0D47A1"}
              - {label: "لون النص الرئيسي", name: "text", widget: "string", default: "#E8F5E9"}
          - label: "الخطوط"
            name: "fonts"
            widget: "object"
            fields:
              - {label: "خط أساسي", name: "base", widget: "string", default: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"}
              - {label: "خط عناوين", name: "heading", widget: "string", default: "'Cairo', sans-serif"}
